spring.application.name=whatsapp-automation-backend
server.port=${SERVER_PORT:8081}

supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_KEY}
supabase.role=${SUPABASE_ROLE}

evolution.url=${EVOLUTION_URL}
evolution.key=${EVOLUTION_KEY}