name: Deploy to K3s

on:
  push:
    branches:
      - master  # or main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Deploy to k3s
        uses: azure/k8s-deploy@v4
        with:
          action: deploy
          strategy: basic
          manifests: |
            k8s/deployment.yaml
            k8s/network.yaml
          images: 'ezdussin/whatsapp-automation-backend:latest'
          kubectl-version: 'latest'
          kubeconfig: ${{ secrets.KUBE_CONFIG }}